---
type: "auv_nn_speed_torch"
trainedFile: "/home/pierre/workspace/uuv_ws/src/mppi_ros/scripts/mppi_tf/torch-training/2022.08.23-15:15:47/nn-velocity_84x128x128x128x128x128x6.pb"
limMax: 1000.
limMin: 1000.
steps: 1
history: 4