type: "auv"
mass: 26.75
model: bluerov2
inertial:
  ixx: 0.7301
  iyy: 0.7705
  izz: 0.8024
  ixy: 0.002048
  ixz: 0.003906
  iyz: 0.001800
cog: [0, 0, 0]
# CoB represented wrt ENU convention
cob: [0, 0, 0.05]
volume: 0.02675
length: 0.457
height: 0.254
width: 0.338
base_link: base_link
frame_id: 'world'
Ma:
- [40, 0., 0., 0., 0., 0.]
- [0., 30, 0., 0., 0., 0.]
- [0., 0., 30, 0., 0., 0.]
- [0., 0., 0., 10, 0., 0.]
- [0., 0., 0., 0., 30, 0.]
- [0., 0., 0., 0., 0., 30]
# In the model, the damping coefficients are pre-multiplied by -1
linear_damping: [-40., -95, -40, -3., -200, -200]
quad_damping: [-150., -200., -135., -2., -10., -10.]
density: 1000.0
rk: 2