---
model_name: "bluerov2-lietorch"
dataset:
  type: "ListDatasetLie"
  dir: "/home/pierre/workspace/uuv_ws/src/mppi_ros/scripts/mppi_tf/data_train/test_train"
  multi_dir: False
  multi_file: True

steps: 15
history: 4
state: [
  'qx', 'qy', 'qz', 'qw',
  'u', 'v', 'w',
  'p', 'q', 'r'
]

action: [
  'Fx', 'Fy', 'Fz',
  'Tx', 'Ty', 'Tz'
]

model:
  type: "liePred"

loss:
  type: "geodesic"


optimizer:
  type: "adam"
  lr: 1.e-4

training_params:
  batch_size: 8192
  shuffle: True
  num_workers: 8

epochs: 1