---
    cost:
      type: quadratic
      w:
        - - 1.0
          - 0.0
          - 0.0
          - 0.0
          - 0.0
          - 0.0
        - - 0.0
          - 1.0
          - 0.0
          - 0.0
          - 0.0
          - 0.0
        - - 0.0
          - 0.0
          - 1.0
          - 0.0
          - 0.0
          - 0.0
        - - 0.0
          - 0.0
          - 0.0
          - 5.0
          - 0.0
          - 0.0
        - - 0.0
          - 0.0
          - 0.0
          - 0.0
          - 5.0
          - 0.0
        - - 0.0
          - 0.0
          - 0.0
          - 0.0
          - 0.0
          - 5.0
    dt: 0.1
    env: ../envs/point_mass3d.xml
    state-dim: 6
    action-dim: 3
    goal:
      - 1.0
      - 0.0
      - 0.5
      - 0.0
      - 0.75
      - 0.0
    horizon: 50
    init-act:
      - 0.0
      - 0.0
      - 0.0
    lambda: 1
    max-a:
      - 1
      - 1
      - 1
    noise:
      - - 0.25
        - 0.0
        - 0.0
      - - 0.0
        - 0.25
        - 0.0
      - - 0.0
        - 0.0
        - 0.25
    samples: 3000
