---
    type: "static_quat"
    diag: true
    goal:
      - 5.0 # x
      - 4.0 # y
      - -50.0 # z
      - 1.0 # qw
      - 0.0 # qx
      - 0.0 # qy
      - 0.0 # qz
      - 0.0 # u
      - 0.0 # v
      - 0.0 # w
      - 0.0 # p
      - 0.0 # q
      - 0.0 # r
    Q:
      - 1000.0 # x
      - 1000.0 # y
      - 1000.0 # z
      - 1000.0 # angle
      - 1.0 # u
      - 1.0 # v
      - 1.0 # w
      - 1.0 # p
      - 1.0 # q
      - 10.0 # r
      
